package cmd

import (
	"encoding/json"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"

	"github.com/hadron-memory/hadron-cli/internal/api/gen"
	"github.com/hadron-memory/hadron-cli/internal/exitcode"
	"github.com/hadron-memory/hadron-cli/internal/skilldoc"
)

// Fixtures for `hadron skill status`. The seam is one query (SkillPlan), so a
// status test is: put real files on a real disk, let the command walk them,
// and assert BOTH halves — the file facts it sent up, and the report it made
// of the classes that came back.

const statusNodeID = "01a0099f949d76a9baf3a16527485475"
const statusSourceURN = "hrn:node:hadronmemory.com:core:tasks:example"

// skillPlanResp builds a SkillPlan response with one entry. class is written
// verbatim so a test can send `null` — the shape a parse failure arrives in.
func skillPlanResp(class, parseFailure string, findings string) string {
	if findings == "" {
		findings = "[]"
	}
	return `{"data":{"skillPlan":{"scanned":1,"judged":1,"entries":[{"urn":"` + statusSourceURN +
		`","nodeId":"` + statusNodeID + `","name":"hadron-example","class":` + class +
		`,"parseFailure":` + parseFailure + `,"movedFrom":null,"findings":` + findings + `}],"orphans":[]}}}`
}

// The one fixture skill, whose parts a status test never needs to vary: what
// varies between these cases is the DIRECTORY it sits in and whether its
// header carries an id.
const (
	statusSkillName = "hadron-example"
	statusSkillDesc = "Use when example."
	statusSkillBody = "# Example\n\nBody text."
)

// writeSkillFile renders a real skill file through the same Render the
// exporter uses, so the bytes on disk are the bytes a generated file has —
// not a hand-written approximation that could agree with a broken parser.
// An empty id writes a pre-§4a header (no `id=` key at all).
func writeSkillFile(t *testing.T, root, dir, id string) string {
	t.Helper()
	rendered, err := skilldoc.Render(id, statusSkillName, statusSourceURN, statusSkillDesc, statusSkillBody)
	if err != nil {
		t.Fatalf("rendering fixture: %v", err)
	}
	if err := os.MkdirAll(filepath.Join(root, dir), 0o755); err != nil {
		t.Fatal(err)
	}
	path := filepath.Join(root, dir, "SKILL.md")
	if err := os.WriteFile(path, []byte(rendered), 0o600); err != nil {
		t.Fatal(err)
	}
	return path
}

// writeUnparseableSkill reproduces the REAL specimen this path exists for: a
// hand-run export wrote an unquoted description containing ": ", so the YAML
// frontmatter does not parse — while the provenance header BELOW it still
// reads perfectly. Three skills in the live corpus are in exactly this state.
func writeUnparseableSkill(t *testing.T, root, dir string) {
	t.Helper()
	const file = "---\n" +
		"name: hadron-example\n" +
		"description: Covers BOTH tracks: the one that breaks the parser.\n" +
		"---\n\n" +
		"<!-- hadron-skill id=" + statusNodeID + " source=" + statusSourceURN + " hash=0123456789abcdef -->\n" +
		"<!-- Edit the source node and re-export; do not edit this file directly. -->\n\n" +
		"# Example\n"
	if err := os.MkdirAll(filepath.Join(root, dir), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(root, dir, "SKILL.md"), []byte(file), 0o600); err != nil {
		t.Fatal(err)
	}
	// The premise of the whole path: this really does fail to parse.
	if _, err := skilldoc.ParseFile([]byte(file)); err == nil {
		t.Fatal("fixture parses cleanly — it no longer exercises the parse-failure path")
	}
}

func runSkillStatus(t *testing.T, responses map[string]string, args ...string) (string, map[string]json.RawMessage, error) {
	t.Helper()
	// `-m` resolves each ref through GetMemory now (the plugin target filters
	// on VISIBILITY, which only a lookup carries), so every -m test needs one.
	// Defaulted here rather than repeated, and still overridable per test.
	if _, ok := responses["GetMemory"]; !ok {
		responses["GetMemory"] = skillMemOrg
	}
	gql, captured := captureGraphQL(t, responses)
	f, out := testFactory(t)
	root := NewRootCmd(f)
	root.SetArgs(append([]string{"skill", "status", "--server", gql.URL}, args...))
	err := root.Execute()
	return out.String(), captured, err
}

// sentFiles decodes the `files` array the command put in the SkillPlan input.
func sentFiles(t *testing.T, captured map[string]json.RawMessage) []map[string]any {
	t.Helper()
	var vars struct {
		Input struct {
			Files    []map[string]any `json:"files"`
			Memories []string         `json:"memories"`
			Host     *string          `json:"host"`
			Intent   string           `json:"intent"`
		} `json:"input"`
	}
	raw, ok := captured["SkillPlan"]
	if !ok {
		t.Fatalf("SkillPlan was never called; captured: %v", captured)
	}
	if err := json.Unmarshal(raw, &vars); err != nil {
		t.Fatalf("decoding SkillPlan vars: %v\n%s", err, raw)
	}
	if vars.Input.Intent != "STATUS" {
		t.Errorf("intent = %q, want STATUS — status must never ask for a rendered body", vars.Input.Intent)
	}
	return vars.Input.Files
}

func sentInput(t *testing.T, captured map[string]json.RawMessage) map[string]any {
	t.Helper()
	var vars struct {
		Input map[string]any `json:"input"`
	}
	if err := json.Unmarshal(captured["SkillPlan"], &vars); err != nil {
		t.Fatalf("decoding SkillPlan vars: %v", err)
	}
	return vars.Input
}

// A parse failure carries NO class, and the report must not let that render as
// a clean row. This is the first assertion in the file on purpose: `class` is
// nullable, and a Go zero value printed into the CLASS column is exactly the
// shape of a failure that looks like success.
func TestSkillStatusParseFailureIsNotRenderedAsAClass(t *testing.T) {
	root := t.TempDir()
	writeUnparseableSkill(t, root, "example")

	out, captured, err := runSkillStatus(t, map[string]string{
		"SkillPlan": skillPlanResp("null", "true", ""),
	}, "-m", "hrn:mem:hadronmemory.com:core", "--to", root, "--json")
	if err != nil {
		t.Fatalf("status errored: %v\n%s", err, out)
	}

	// The client told the server the file is there and would not parse.
	files := sentFiles(t, captured)
	if len(files) != 1 {
		t.Fatalf("want 1 file fact, got %d: %v", len(files), files)
	}
	if files[0]["parseFailed"] != true {
		t.Errorf("parseFailed not sent for an unparseable file: %v", files[0])
	}
	if _, present := files[0]["fileHash"]; present {
		t.Errorf("a file that did not parse cannot have a fileHash: %v", files[0])
	}
	// THE defect this path exists for: the pairing key lives inside the file
	// that will not parse. Recovered from the header below the frontmatter, the
	// failure is attributed to its node; dropped, the server can only call the
	// file an ORPHAN — a claim that a real skill belongs to no node, and what
	// `export --prune` deletes. Measured on the live corpus: three skills.
	if files[0]["nodeId"] != statusNodeID {
		t.Errorf("nodeId not recovered from a file whose frontmatter failed — "+
			"the parse failure will be reported as an orphan: %v", files[0])
	}
	if files[0]["sourceUrn"] != statusSourceURN {
		t.Errorf("sourceUrn not recovered from a failed parse: %v", files[0])
	}

	// --json keeps the null: it is what the server said.
	var dto struct {
		Entries []struct {
			Class        *string `json:"class"`
			ParseFailure bool    `json:"parseFailure"`
		} `json:"entries"`
	}
	if err := json.Unmarshal([]byte(out), &dto); err != nil {
		t.Fatalf("output not JSON: %v\n%s", err, out)
	}
	if len(dto.Entries) != 1 {
		t.Fatalf("want 1 entry, got %d", len(dto.Entries))
	}
	if dto.Entries[0].Class != nil {
		t.Errorf("class = %q, want null — a parse failure has no class", *dto.Entries[0].Class)
	}
	if !dto.Entries[0].ParseFailure {
		t.Error("parseFailure lost between the wire and the DTO")
	}
}

// The same case in the human view: the CLASS cell must not be blank-and-clean.
func TestSkillStatusParseFailureIsVisibleInTheTable(t *testing.T) {
	root := t.TempDir()
	writeUnparseableSkill(t, root, "example")
	out, _, err := runSkillStatus(t, map[string]string{
		"SkillPlan": skillPlanResp("null", "true", ""),
	}, "-m", "hrn:mem:hadronmemory.com:core", "--to", root)
	if err != nil {
		t.Fatalf("status errored: %v\n%s", err, out)
	}
	if !strings.Contains(out, "file does not parse") {
		t.Errorf("a parse failure is invisible in the table:\n%s", out)
	}
	// And the CLASS cell carries the absence marker rather than a blank. A
	// blank cell is what a Go zero value renders as, and it makes an
	// unparseable file read as an ordinary clean row — the failure wearing the
	// appearance of success. Asserted on the CELL, not on the line, because
	// "-" occurs elsewhere in a URN.
	var classCell string
	for _, line := range strings.Split(out, "\n") {
		if strings.HasPrefix(line, "hadron-example") {
			if fields := strings.Fields(line); len(fields) > 1 {
				classCell = fields[1]
			}
		}
	}
	// The RELATIONSHIP is what is pinned, not the literal: the cell must differ
	// from both a blank and from every class the server can send. Asserting the
	// literal alone still passes after somebody "tidies" the token back to "",
	// which is the state this guards against.
	if classCell == "" {
		t.Errorf("CLASS cell is blank — a parse failure renders as an ordinary clean row:\n%s", out)
	}
	for _, real := range []string{
		"current", "stale", "locally-edited", "renamed", "never-exported",
		"orphaned", "unhashed", "collision", "unavailable", "disabled",
	} {
		if classCell == real {
			t.Errorf("CLASS cell = %q — an absent class must not render as one of the ten classes", classCell)
		}
	}
}

// An untouched generated file hashes to exactly what its header records — that
// identity is what makes `locally-edited` detectable at all, so it is asserted
// rather than assumed.
func TestSkillStatusSendsFileFactsThatMatchAnUntouchedFile(t *testing.T) {
	root := t.TempDir()
	writeSkillFile(t, root, "hadron-example", statusNodeID)

	out, captured, err := runSkillStatus(t, map[string]string{
		"SkillPlan": skillPlanResp(`"current"`, "false", ""),
	}, "-m", "hrn:mem:hadronmemory.com:core", "--to", root, "--json")
	if err != nil {
		t.Fatalf("status errored: %v\n%s", err, out)
	}
	files := sentFiles(t, captured)
	if len(files) != 1 {
		t.Fatalf("want 1 file fact, got %d: %v", len(files), files)
	}
	f := files[0]
	if f["dirName"] != "hadron-example" {
		t.Errorf("dirName = %v", f["dirName"])
	}
	if f["nodeId"] != statusNodeID {
		t.Errorf("nodeId = %v, want the header id — the §4a pairing key", f["nodeId"])
	}
	if f["sourceUrn"] != statusSourceURN {
		t.Errorf("sourceUrn = %v", f["sourceUrn"])
	}
	if f["fileHash"] != f["headerHash"] {
		t.Errorf("an untouched file must hash to its own header: file=%v header=%v", f["fileHash"], f["headerHash"])
	}
	if _, present := f["hasExtraFrontmatter"]; present {
		t.Errorf("a generated file carries no extra frontmatter: %v", f)
	}
}

// The detection that matters: a hand-edited body no longer hashes to its
// header. Without this the server could never return `locally-edited`, and
// export would overwrite somebody's work and call it success.
func TestSkillStatusLocalEditMakesFileHashDivergeFromHeader(t *testing.T) {
	root := t.TempDir()
	path := writeSkillFile(t, root, "hadron-example", statusNodeID)
	data, err := os.ReadFile(path) // #nosec G304 — test fixture
	if err != nil {
		t.Fatal(err)
	}
	edited := string(data) + "\nA line somebody added by hand.\n"
	if err := os.WriteFile(path, []byte(edited), 0o600); err != nil {
		t.Fatal(err)
	}

	_, captured, err := runSkillStatus(t, map[string]string{
		"SkillPlan": skillPlanResp(`"locally-edited"`, "false", ""),
	}, "-m", "hrn:mem:hadronmemory.com:core", "--to", root, "--json")
	if err != nil {
		t.Fatalf("status errored: %v", err)
	}
	f := sentFiles(t, captured)[0]
	if f["fileHash"] == f["headerHash"] {
		t.Errorf("a hand-edited file still hashes to its header — the edit is undetectable: %v", f)
	}
	if f["headerHash"] == nil || f["headerHash"] == "" {
		t.Errorf("headerHash must still travel for an edited file, or the server cannot compare: %v", f)
	}
}

// A file with no Hadron provenance header is somebody else's skill: it is not
// sent, not classified and not reported. The negative matters — reporting one
// invites a user to "fix" a file this tool has no business touching.
func TestSkillStatusIgnoresAFileItDidNotGenerate(t *testing.T) {
	root := t.TempDir()
	if err := os.MkdirAll(filepath.Join(root, "someone-elses"), 0o755); err != nil {
		t.Fatal(err)
	}
	foreign := "---\nname: someone-elses\ndescription: Use when hand-written.\n---\n\n# Mine\n"
	if err := os.WriteFile(filepath.Join(root, "someone-elses", "SKILL.md"), []byte(foreign), 0o600); err != nil {
		t.Fatal(err)
	}
	// A directory with no SKILL.md at all is likewise not a skill.
	if err := os.MkdirAll(filepath.Join(root, "not-a-skill"), 0o755); err != nil {
		t.Fatal(err)
	}

	_, captured, err := runSkillStatus(t, map[string]string{
		"SkillPlan": `{"data":{"skillPlan":{"scanned":0,"judged":0,"entries":[],"orphans":[]}}}`,
	}, "-m", "hrn:mem:hadronmemory.com:core", "--to", root, "--json")
	if err != nil {
		t.Fatalf("status errored: %v", err)
	}
	if files := sentFiles(t, captured); len(files) != 0 {
		t.Errorf("a non-Hadron skill must be invisible, got %v", files)
	}
}

// Drift alone exits 0; --strict is the CI gate that turns it into 5.
func TestSkillStatusStrictIsWhatTurnsDriftIntoAnExitCode(t *testing.T) {
	root := t.TempDir()
	writeSkillFile(t, root, "hadron-example", statusNodeID)
	responses := map[string]string{"SkillPlan": skillPlanResp(`"stale"`, "false", "")}

	if _, _, err := runSkillStatus(t, responses, "-m", "hrn:mem:hadronmemory.com:core", "--to", root); exitCodeFor(err) != exitcode.OK {
		t.Fatalf("drift without --strict must exit 0, got %v", err)
	}
	_, _, err := runSkillStatus(t, responses, "-m", "hrn:mem:hadronmemory.com:core", "--to", root, "--strict")
	if got := exitCodeFor(err); got != exitcode.Conflict {
		t.Fatalf("drift under --strict: exit = %d, want %d", got, exitcode.Conflict)
	}
}

// `current` is not drift, so --strict on a clean set still exits 0. Without
// this, the --strict test above would pass for a gate that fails on anything.
func TestSkillStatusStrictExitsZeroWhenEverythingIsCurrent(t *testing.T) {
	root := t.TempDir()
	writeSkillFile(t, root, "hadron-example", statusNodeID)
	_, _, err := runSkillStatus(t, map[string]string{
		"SkillPlan": skillPlanResp(`"current"`, "false", ""),
	}, "-m", "hrn:mem:hadronmemory.com:core", "--to", root, "--strict")
	if got := exitCodeFor(err); got != exitcode.OK {
		t.Fatalf("a current corpus under --strict: exit = %d, want 0", got)
	}
}

// An ERROR finding exits 5 with no --strict at all, as in `skill lint`.
func TestSkillStatusErrorFindingExitsConflictWithoutStrict(t *testing.T) {
	root := t.TempDir()
	finding := `[{"rule":"skill-name-invalid","severity":"error","message":"not kebab-case","urn":"` +
		statusSourceURN + `","memory":"hrn:mem:hadronmemory.com:core"}]`
	_, _, err := runSkillStatus(t, map[string]string{
		"SkillPlan": skillPlanResp(`"current"`, "false", finding),
	}, "-m", "hrn:mem:hadronmemory.com:core", "--to", root)
	if got := exitCodeFor(err); got != exitcode.Conflict {
		t.Fatalf("exit = %d, want %d (Conflict) for an error finding", got, exitcode.Conflict)
	}
}

// An orphan is drift: a file paired with nothing is exactly what the gate is
// for, and it arrives outside `entries`.
func TestSkillStatusOrphanCountsAsDriftUnderStrict(t *testing.T) {
	root := t.TempDir()
	resp := `{"data":{"skillPlan":{"scanned":0,"judged":0,"entries":[],"orphans":[{"dirName":"gone","nodeId":null,"sourceUrn":"` +
		statusSourceURN + `"}]}}}`
	out, _, err := runSkillStatus(t, map[string]string{"SkillPlan": resp},
		"-m", "hrn:mem:hadronmemory.com:core", "--to", root, "--strict")
	if got := exitCodeFor(err); got != exitcode.Conflict {
		t.Fatalf("exit = %d, want %d for an orphan under --strict", got, exitcode.Conflict)
	}
	if !strings.Contains(out, "gone") {
		t.Errorf("the orphan is not named in the report:\n%s", out)
	}
}

// A missing skills root is "nothing exported yet", not a failure — and the
// report still names the root, so an empty answer is never mistaken for a
// wrong one.
func TestSkillStatusMissingRootIsNotAnError(t *testing.T) {
	missing := filepath.Join(t.TempDir(), "never-created")
	out, captured, err := runSkillStatus(t, map[string]string{
		"SkillPlan": `{"data":{"skillPlan":{"scanned":0,"judged":0,"entries":[],"orphans":[]}}}`,
	}, "-m", "hrn:mem:hadronmemory.com:core", "--to", missing)
	if err != nil {
		t.Fatalf("a missing root must not error: %v\n%s", err, out)
	}
	if files := sentFiles(t, captured); len(files) != 0 {
		t.Errorf("a missing root has no files, got %v", files)
	}
	if !strings.Contains(out, missing) {
		t.Errorf("the report does not name the root it walked:\n%s", out)
	}
}

// An empty corpus and one the caller cannot see are the same empty list, so
// the count the server sends to tell them apart has to reach the reader.
func TestSkillStatusEmptyPlanReportsWhatWasInScope(t *testing.T) {
	out, _, err := runSkillStatus(t, map[string]string{
		"SkillPlan": `{"data":{"skillPlan":{"scanned":7,"judged":0,"entries":[],"orphans":[]}}}`,
	}, "-m", "hrn:mem:hadronmemory.com:core", "--to", t.TempDir())
	if err != nil {
		t.Fatalf("status errored: %v", err)
	}
	// Asserted on the whole PHRASE, not on the bare digit: the report also
	// prints the root path, and a temp directory happens to contain digits —
	// so `Contains(out, "7")` passes whatever the count actually is.
	if !strings.Contains(out, "7 node(s) carrying a declaration were in scope") {
		t.Errorf("the scanned count is not reported, so a denied corpus reads as a clean one:\n%s", out)
	}
}

// --all expands to the explicit memory refs this CLI means by it, rather than
// omitting the field and inheriting the server's own definition of "all".
func TestSkillStatusAllSendsExplicitMemoryRefs(t *testing.T) {
	memories := `{"data":{"memories":{"total":1,"items":[{"id":"mem1","urn":"hrn:mem:hadronmemory.com:core","name":"Core","shortDescription":null,"class":"knowledge","visibility":"PUBLIC","organizationId":"org1","organization":{"skillPrefix":"hadron-"},"isEncrypted":false,"maxRevCount":null,"updatedAt":"2026-06-11T00:00:00Z"}]}}}`
	shared := `{"data":{"memories":{"total":0,"items":[]}}}`
	_, captured, err := runSkillStatus(t, map[string]string{
		"Memories": memories, "MemoriesSharedWithMe": shared,
		"SkillPlan": `{"data":{"skillPlan":{"scanned":0,"judged":0,"entries":[],"orphans":[]}}}`,
	}, "--all", "--to", t.TempDir(), "--json")
	if err != nil {
		t.Fatalf("status errored: %v", err)
	}
	input := sentInput(t, captured)
	mems, _ := input["memories"].([]any)
	if len(mems) != 1 || mems[0] != "hrn:mem:hadronmemory.com:core" {
		t.Errorf("--all did not send the listed memories explicitly: %v", input["memories"])
	}
}

// The host travels by its PROPERTY KEY, so `--host claude` and
// exports.claudeSkill never need a mapping table nobody maintains.
func TestSkillStatusSendsHostVerbatim(t *testing.T) {
	_, captured, err := runSkillStatus(t, map[string]string{
		"SkillPlan": `{"data":{"skillPlan":{"scanned":0,"judged":0,"entries":[],"orphans":[]}}}`,
	}, "-m", "hrn:mem:hadronmemory.com:core", "--to", t.TempDir())
	if err != nil {
		t.Fatalf("status errored: %v", err)
	}
	if got := sentInput(t, captured)["host"]; got != "claudeSkill" {
		t.Errorf("host = %v, want claudeSkill (the property key, not a display name)", got)
	}
}

// One of the two memory-wide selectors is required: no active-memory fallback,
// because a status that silently targets "whatever was active" answers a
// question the user did not ask.
func TestSkillStatusSelectorIsRequiredAndExclusive(t *testing.T) {
	for _, tc := range []struct {
		name string
		args []string
	}{
		{"neither", []string{"--to", t.TempDir()}},
		{"both", []string{"--all", "-m", "hrn:mem:hadronmemory.com:core", "--to", t.TempDir()}},
		{"empty memory", []string{"-m", "  ", "--to", t.TempDir()}},
	} {
		t.Run(tc.name, func(t *testing.T) {
			f, out := testFactory(t)
			root := NewRootCmd(f)
			root.SetArgs(append([]string{"skill", "status"}, tc.args...))
			err := root.Execute()
			if got := exitCodeFor(err); got != exitcode.Usage {
				t.Fatalf("exit = %d, want %d (Usage); out=%s", got, exitcode.Usage, out.String())
			}
		})
	}
}

// status takes no --node by design (§3). Asserted so a later "consistency"
// change cannot quietly add one: the orphan and collision classes are
// properties of a SET, and a one-node status could not report them.
func TestSkillStatusHasNoNodeSelector(t *testing.T) {
	f, out := testFactory(t)
	root := NewRootCmd(f)
	root.SetArgs([]string{"skill", "status", "--node", "01a0099f949d76a9baf3a16527485475", "--to", t.TempDir()})
	err := root.Execute()
	if got := exitCodeFor(err); got != exitcode.Usage {
		t.Fatalf("--node should be an unknown flag on status: exit = %d, want %d; out=%s", got, exitcode.Usage, out.String())
	}
	// And lint still HAS it — the two verbs differ on purpose, so this is a
	// control rather than a claim about the whole group.
	f2, _ := testFactory(t)
	if lint, _, err := NewRootCmd(f2).Find([]string{"skill", "lint"}); err != nil {
		t.Fatal(err)
	} else if lint.Flags().Lookup("node") == nil {
		t.Error("skill lint lost its --node flag; the asymmetry above is now meaningless")
	}
}

// A pre-§4a file carries no `id=` at all. Two things must hold, and both are
// cross-implementation conventions rather than local choices: `nodeId` is
// OMITTED (never sent blank), and the fileHash is computed with the id as the
// EMPTY STRING rather than skipped — which is what keeps such a file
// self-consistent against its own header instead of reading as edited.
func TestSkillStatusLegacyHeaderOmitsNodeIdAndStaysSelfConsistent(t *testing.T) {
	root := t.TempDir()
	writeSkillFile(t, root, "hadron-example", "")

	_, captured, err := runSkillStatus(t, map[string]string{
		"SkillPlan": skillPlanResp(`"unhashed"`, "false", ""),
	}, "-m", "hrn:mem:hadronmemory.com:core", "--to", root, "--json")
	if err != nil {
		t.Fatalf("status errored: %v", err)
	}
	f := sentFiles(t, captured)[0]
	if _, present := f["nodeId"]; present {
		t.Errorf("nodeId must be OMITTED for a pre-§4a header, not sent blank: %v", f)
	}
	if f["sourceUrn"] != statusSourceURN {
		t.Errorf("the URN is the pairing FALLBACK for a file with no id, and it did not travel: %v", f)
	}
	if f["fileHash"] != f["headerHash"] {
		t.Errorf("an untouched pre-§4a file must still hash to its own header "+
			"(empty id hashes as the empty string, it is not skipped): file=%v header=%v",
			f["fileHash"], f["headerHash"])
	}
}

// The DIRECTORY is what travels as dirName, not the stored name. They differ
// exactly when a skill has been renamed in the corpus, which is the whole
// basis of the `renamed` class — so sending the name here would make a rename
// undetectable while every other assertion still passed.
func TestSkillStatusSendsTheDirectoryNotTheStoredName(t *testing.T) {
	root := t.TempDir()
	writeSkillFile(t, root, "the-old-directory", statusNodeID)

	resp := `{"data":{"skillPlan":{"scanned":1,"judged":1,"entries":[{"urn":"` + statusSourceURN +
		`","nodeId":"` + statusNodeID + `","name":"hadron-example","class":"renamed","parseFailure":false,` +
		`"movedFrom":"the-old-directory","findings":[]}],"orphans":[]}}}`
	out, captured, err := runSkillStatus(t, map[string]string{"SkillPlan": resp},
		"-m", "hrn:mem:hadronmemory.com:core", "--to", root)
	if err != nil {
		t.Fatalf("status errored: %v\n%s", err, out)
	}
	f := sentFiles(t, captured)[0]
	if f["dirName"] != "the-old-directory" {
		t.Errorf("dirName = %v, want the DIRECTORY — a rename is invisible if the stored name is sent", f["dirName"])
	}
	// And the server's movedFrom reaches the reader, or a rename is reported
	// as a bare class with nothing to act on.
	if !strings.Contains(out, "was the-old-directory") {
		t.Errorf("movedFrom is not rendered:\n%s", out)
	}
}

// A file that is present and unreadable is an I/O failure, not a parse
// failure, and must not silently become "never exported" — a false statement
// about a disk the server cannot see.
func TestSkillStatusUnreadableFileIsReportedButNotSent(t *testing.T) {
	if runtime.GOOS == "windows" {
		t.Skip("chmod-based unreadability is a POSIX behaviour")
	}
	if os.Geteuid() == 0 {
		t.Skip("root reads a 0000 file regardless, so the fixture cannot be made unreadable")
	}
	root := t.TempDir()
	path := writeSkillFile(t, root, "hadron-example", statusNodeID)
	if err := os.Chmod(path, 0o000); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = os.Chmod(path, 0o600) })

	out, captured, err := runSkillStatus(t, map[string]string{
		"SkillPlan": `{"data":{"skillPlan":{"scanned":0,"judged":0,"entries":[],"orphans":[]}}}`,
	}, "-m", "hrn:mem:hadronmemory.com:core", "--to", root)
	if err != nil {
		t.Fatalf("status errored: %v\n%s", err, out)
	}
	// It is NOT sent: with no bytes there is no provenance, so any claim about
	// it — including "orphan" — would be made on no evidence. It is reported
	// locally instead, with the errno, because silently working around a file
	// we could not read is the one outcome to avoid.
	if files := sentFiles(t, captured); len(files) != 0 {
		t.Errorf("an unreadable file must not be sent as a fact: %v", files)
	}
	if !strings.Contains(out, "Unreadable") {
		t.Errorf("the I/O error is not reported at all:\n%s", out)
	}
}

// Unparseable AND carrying no provenance: we cannot tell it is ours, so it is
// not sent — but it is still shown. Without the report it would be silently
// skipped, which is how a broken file goes unnoticed for a month.
func TestSkillStatusUnattributableFileIsReportedButNotSent(t *testing.T) {
	root := t.TempDir()
	if err := os.MkdirAll(filepath.Join(root, "mystery"), 0o755); err != nil {
		t.Fatal(err)
	}
	// No terminating `---`, so there is no frontmatter and no header to find.
	if err := os.WriteFile(filepath.Join(root, "mystery", "SKILL.md"), []byte("---\nname: broken\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	out, captured, err := runSkillStatus(t, map[string]string{
		"SkillPlan": `{"data":{"skillPlan":{"scanned":0,"judged":0,"entries":[],"orphans":[]}}}`,
	}, "-m", "hrn:mem:hadronmemory.com:core", "--to", root, "--strict")
	if got := exitCodeFor(err); got != exitcode.Conflict {
		t.Fatalf("an unparseable file is drift: exit = %d, want %d", got, exitcode.Conflict)
	}
	if files := sentFiles(t, captured); len(files) != 0 {
		t.Errorf("an unattributable file must not be sent — it would be called an orphan on no evidence: %v", files)
	}
	if !strings.Contains(out, "mystery") {
		t.Errorf("an unparseable file was skipped silently:\n%s", out)
	}
}

// STATUS must never ask for a rendered body: `skillPlan` returns one only for
// EXPORT, and a status that requested it would be a read verb holding the
// bytes of a write. Both the query's own comment and this PR's description say
// so, which makes this test the only thing keeping that claim true.
//
// Asserted against the GENERATED OPERATION — the text that goes on the wire —
// because captureGraphQL records request VARIABLES only, so a search of
// captured["SkillPlan"] for a field name can never fail
// (review:assert-the-query-not-the-capture). Field-exact rather than a
// substring, so a longer sibling field could not satisfy it.
func TestSkillPlanQueryNeverSelectsRenderedBody(t *testing.T) {
	for _, line := range strings.Split(gen.SkillPlan_Operation, "\n") {
		if strings.TrimSpace(line) == "renderedBody" {
			t.Errorf("status's query selects renderedBody:\n%s", gen.SkillPlan_Operation)
		}
	}
	// A control: the assertion is looking at a document that really does carry
	// the neighbouring fields, so a green result means "absent", not "looked in
	// the wrong place".
	var sawClass bool
	for _, line := range strings.Split(gen.SkillPlan_Operation, "\n") {
		if strings.TrimSpace(line) == "class" {
			sawClass = true
		}
	}
	if !sawClass {
		t.Fatal("control failed: the operation does not select `class` either, so this test proves nothing")
	}
}

// @codex on #652: `SkillPlanInput.Memories` carries `omitempty`, so an EMPTY
// slice is omitted from the wire — and the schema defines an omitted
// `memories` as EVERY memory the caller can read. So the one case where this
// client has decided the scope is empty is exactly the case where the request
// would silently widen to the opposite, re-including the memories --all
// deliberately excludes. The fix is to not send the request at all.
func TestSkillStatusEmptyAllScopeIsNotSentAsEveryMemory(t *testing.T) {
	empty := `{"data":{"memories":{"total":0,"items":[]}}}`
	out, captured, err := runSkillStatus(t, map[string]string{
		"Memories": empty, "MemoriesSharedWithMe": empty,
	}, "--all", "--to", t.TempDir())
	if err != nil {
		t.Fatalf("status errored: %v\n%s", err, out)
	}
	if raw, called := captured["SkillPlan"]; called {
		t.Errorf("an empty --all scope was sent, and `memories` omitempty widens it "+
			"back to every readable memory: %s", raw)
	}
	// And it must not read as an all-clear.
	if !strings.Contains(out, "not an all-clear") {
		t.Errorf("an empty scope reports as a clean corpus:\n%s", out)
	}
}

// Proof the guard above is not vacuous: a NON-empty --all really does send.
func TestSkillStatusNonEmptyAllScopeIsSent(t *testing.T) {
	memories := `{"data":{"memories":{"total":1,"items":[{"id":"mem1","urn":"hrn:mem:hadronmemory.com:core","name":"Core","shortDescription":null,"class":"knowledge","visibility":"PUBLIC","organizationId":"org1","organization":{"skillPrefix":"hadron-"},"isEncrypted":false,"maxRevCount":null,"updatedAt":"2026-06-11T00:00:00Z"}]}}}`
	_, captured, err := runSkillStatus(t, map[string]string{
		"Memories": memories, "MemoriesSharedWithMe": `{"data":{"memories":{"total":0,"items":[]}}}`,
		"SkillPlan": `{"data":{"skillPlan":{"scanned":0,"judged":0,"entries":[],"orphans":[]}}}`,
	}, "--all", "--to", t.TempDir())
	if err != nil {
		t.Fatalf("status errored: %v", err)
	}
	if _, called := captured["SkillPlan"]; !called {
		t.Fatal("control failed: a non-empty scope did not send either, so the guard proves nothing")
	}
}

// @codex on #652: the committed plugin bundle lives in a PUBLIC repo and may
// carry PUBLIC memories only (D9/§6). Without the filter, `--all --to plugin
// --strict` — the documented CI gate — compares a private memory's
// declarations against the public directory and fails on a current bundle.
func TestSkillStatusPluginTargetKeepsOnlyPublicMemories(t *testing.T) {
	mem := func(id, urn, vis string) string {
		return `{"id":"` + id + `","urn":"` + urn + `","name":"M","shortDescription":null,"class":"knowledge","visibility":"` + vis +
			`","organizationId":"org1","organization":{"skillPrefix":null},"isEncrypted":false,"maxRevCount":null,"updatedAt":"2026-06-11T00:00:00Z"}`
	}
	memories := `{"data":{"memories":{"total":2,"items":[` +
		mem("mem1", "hrn:mem:hadronmemory.com:core", "PUBLIC") + `,` +
		mem("mem2", "hrn:mem:micromentor.org:mmdata", "ORGANIZATION") + `]}}}`
	// A git worktree is required for --to plugin; this repo is one.
	out, captured, err := runSkillStatus(t, map[string]string{
		"Memories": memories, "MemoriesSharedWithMe": `{"data":{"memories":{"total":0,"items":[]}}}`,
		"SkillPlan": `{"data":{"skillPlan":{"scanned":0,"judged":0,"entries":[],"orphans":[]}}}`,
	}, "--all", "--to", "plugin", "--json")
	if err != nil {
		t.Fatalf("status errored: %v\n%s", err, out)
	}
	mems, _ := sentInput(t, captured)["memories"].([]any)
	if len(mems) != 1 || mems[0] != "hrn:mem:hadronmemory.com:core" {
		t.Errorf("the plugin target scanned a non-PUBLIC memory: %v", mems)
	}
	// Excluded, not silently dropped: a short result must not read as a clean
	// corpus.
	var dto struct {
		Excluded []struct{ Memory, Reason string } `json:"excluded"`
	}
	if err := json.Unmarshal([]byte(out), &dto); err != nil {
		t.Fatalf("output not JSON: %v\n%s", err, out)
	}
	if len(dto.Excluded) != 1 || dto.Excluded[0].Memory != "hrn:mem:micromentor.org:mmdata" {
		t.Errorf("the excluded memory is not reported: %+v", dto.Excluded)
	}
}

// The same two memories under a NON-plugin target are both in scope — so the
// filter above is the plugin rule, not a blanket one.
func TestSkillStatusUserTargetKeepsPrivateMemories(t *testing.T) {
	mem := func(id, urn, vis string) string {
		return `{"id":"` + id + `","urn":"` + urn + `","name":"M","shortDescription":null,"class":"knowledge","visibility":"` + vis +
			`","organizationId":"org1","organization":{"skillPrefix":null},"isEncrypted":false,"maxRevCount":null,"updatedAt":"2026-06-11T00:00:00Z"}`
	}
	memories := `{"data":{"memories":{"total":2,"items":[` +
		mem("mem1", "hrn:mem:hadronmemory.com:core", "PUBLIC") + `,` +
		mem("mem2", "hrn:mem:micromentor.org:mmdata", "ORGANIZATION") + `]}}}`
	_, captured, err := runSkillStatus(t, map[string]string{
		"Memories": memories, "MemoriesSharedWithMe": `{"data":{"memories":{"total":0,"items":[]}}}`,
		"SkillPlan": `{"data":{"skillPlan":{"scanned":0,"judged":0,"entries":[],"orphans":[]}}}`,
	}, "--all", "--to", t.TempDir())
	if err != nil {
		t.Fatalf("status errored: %v", err)
	}
	if mems, _ := sentInput(t, captured)["memories"].([]any); len(mems) != 2 {
		t.Errorf("--to <dir> must not apply the plugin visibility rule, got %v", mems)
	}
}

// @codex on #652: `--host` is accepted verbatim, but the symbolic roots are
// Claude's. `--host codex --to user` would compare one host's declarations
// against ~/.claude/skills, making every orphan and drift row an artifact of
// the mismatch. A loud refusal beats a permissive resolve; an explicit
// directory stays the override, so a second host is testable before it has a
// root of its own.
func TestSkillStatusRefusesASymbolicRootForAHostWithoutOne(t *testing.T) {
	for _, to := range []string{"user", "project", "plugin"} {
		t.Run(to, func(t *testing.T) {
			f, out := testFactory(t)
			root := NewRootCmd(f)
			root.SetArgs([]string{"skill", "status", "--all", "--host", "codex", "--to", to})
			if got := exitCodeFor(root.Execute()); got != exitcode.Usage {
				t.Fatalf("exit = %d, want %d (Usage); out=%s", got, exitcode.Usage, out.String())
			}
		})
	}
}

// ...and an explicit directory is accepted for that same host, or the refusal
// above would just be "no second host at all".
func TestSkillStatusAllowsAnExplicitDirForAnyHost(t *testing.T) {
	_, captured, err := runSkillStatus(t, map[string]string{
		"SkillPlan": `{"data":{"skillPlan":{"scanned":0,"judged":0,"entries":[],"orphans":[]}}}`,
	}, "-m", "hrn:mem:hadronmemory.com:core", "--host", "codex", "--to", t.TempDir())
	if err != nil {
		t.Fatalf("an explicit --to <dir> must work for any host: %v", err)
	}
	if got := sentInput(t, captured)["host"]; got != "codex" {
		t.Errorf("host = %v, want codex passed through verbatim", got)
	}
}

// @codex on #652, round 2 — a regression introduced by the FIX for the
// empty-scope widening. Short-circuiting the request discarded the
// provenance-bearing files already found on disk, so `--all --to plugin
// --strict` (the documented CI gate) exited 0 while generated skills sat in
// the target unpaired and unexamined. A gate must not pass on a result
// nothing checked.
func TestSkillStatusEmptyScopeFailsStrictAndNamesWhatWentUnchecked(t *testing.T) {
	root := t.TempDir()
	writeSkillFile(t, root, "hadron-example", statusNodeID)
	empty := `{"data":{"memories":{"total":0,"items":[]}}}`
	responses := func() map[string]string {
		return map[string]string{"Memories": empty, "MemoriesSharedWithMe": empty}
	}

	// Under --strict it must FAIL: nothing was verified.
	out, captured, err := runSkillStatus(t, responses(), "--all", "--to", root, "--strict")
	if got := exitCodeFor(err); got != exitcode.Conflict {
		t.Fatalf("an empty scope passed --strict: exit = %d, want %d\n%s", got, exitcode.Conflict, out)
	}
	if _, called := captured["SkillPlan"]; called {
		t.Error("the empty scope was still sent, which is the widening this guard replaced")
	}
	// And the file on disk must be NAMED, not silently dropped.
	if !strings.Contains(out, "hadron-example") {
		t.Errorf("a generated file went unchecked and unnamed:\n%s", out)
	}

	// The --json contract carries both facts.
	out2, _, err := runSkillStatus(t, responses(), "--all", "--to", root, "--json")
	if err != nil {
		t.Fatalf("without --strict an empty scope still reports: %v", err)
	}
	var dto struct {
		ScopeEmpty bool                           `json:"scopeEmpty"`
		Unchecked  []struct{ Dir, Source string } `json:"unchecked"`
	}
	if err := json.Unmarshal([]byte(out2), &dto); err != nil {
		t.Fatalf("output not JSON: %v\n%s", err, out2)
	}
	if !dto.ScopeEmpty {
		t.Error("scopeEmpty is false for a report that asked the server nothing")
	}
	if len(dto.Unchecked) != 1 || dto.Unchecked[0].Dir != "hadron-example" {
		t.Errorf("the unchecked file is missing from --json: %+v", dto.Unchecked)
	}
	if dto.Unchecked[0].Source != statusSourceURN {
		t.Errorf("unchecked entry lost its provenance: %+v", dto.Unchecked[0])
	}
}

// The plugin path that motivated it: every listed memory is private, so the
// scope empties AFTER filtering and the gate would otherwise go green.
func TestSkillStatusPluginGateFailsWhenFilteringEmptiesTheScope(t *testing.T) {
	memories := `{"data":{"memories":{"total":1,"items":[{"id":"mem2","urn":"hrn:mem:micromentor.org:mmdata","name":"M","shortDescription":null,"class":"knowledge","visibility":"ORGANIZATION","organizationId":"org1","organization":{"skillPrefix":null},"isEncrypted":false,"maxRevCount":null,"updatedAt":"2026-06-11T00:00:00Z"}]}}}`
	out, captured, err := runSkillStatus(t, map[string]string{
		"Memories": memories, "MemoriesSharedWithMe": `{"data":{"memories":{"total":0,"items":[]}}}`,
	}, "--all", "--to", "plugin", "--strict")
	if got := exitCodeFor(err); got != exitcode.Conflict {
		t.Fatalf("the plugin gate went green on an empty post-filter scope: exit = %d, want %d\n%s",
			got, exitcode.Conflict, out)
	}
	if _, called := captured["SkillPlan"]; called {
		t.Error("an all-private selection should not reach the server")
	}
	if !strings.Contains(out, "mmdata") {
		t.Errorf("the excluded memory is not named, so the empty result looks unexplained:\n%s", out)
	}
}

// @codex on #652, round 2: --help promised a file with no Hadron header is
// "never listed". False for one that does not PARSE — it is reported as
// unparseable and counts as drift. The claim had been corrected in
// agentic-usage.md and not in the command's own help, which is the surface a
// user actually reads.
func TestSkillStatusHelpQualifiesTheForeignFilePromise(t *testing.T) {
	f, _ := testFactory(t)
	cmd, _, err := NewRootCmd(f).Find([]string{"skill", "status"})
	if err != nil {
		t.Fatal(err)
	}
	long := cmd.Long
	if strings.Contains(long, "A file with no Hadron header is somebody else's skill") {
		t.Error("help still makes the unqualified promise")
	}
	if !strings.Contains(long, "PARSES") {
		t.Error("help does not qualify the promise to files that parse")
	}
	if !strings.Contains(long, "unparseable") {
		t.Error("help never tells the reader an unparseable foreign file IS reported")
	}
}

// @codex on #652: --strict PROMOTES warnings — the group's contract (§3), and
// what `skill lint --strict` already does. A `current` entry carrying only a
// warning left both flags false, so the CI gate passed a warned corpus and the
// SAME finding produced a different exit code depending on which verb reported
// it. An inconsistent contract across one command group is a real defect, not
// a cosmetic one.
func TestSkillStatusStrictPromotesWarningFindings(t *testing.T) {
	root := t.TempDir()
	writeSkillFile(t, root, "hadron-example", statusNodeID)
	warning := `[{"rule":"skill-description-no-trigger","severity":"warning","message":"no use-when phrasing","urn":"` +
		statusSourceURN + `","memory":"hrn:mem:hadronmemory.com:core"}]`
	// `current` class, so the ONLY thing that can fail the gate is the warning.
	responses := func() map[string]string {
		return map[string]string{"SkillPlan": skillPlanResp(`"current"`, "false", warning)}
	}

	// Without --strict a warning alone is exit 0, exactly as in skill lint.
	if _, _, err := runSkillStatus(t, responses(), "-m", "hrn:mem:hadronmemory.com:core", "--to", root); exitCodeFor(err) != exitcode.OK {
		t.Fatalf("a warning alone must exit 0 without --strict, got %v", err)
	}
	// With --strict it is promoted.
	_, _, err := runSkillStatus(t, responses(), "-m", "hrn:mem:hadronmemory.com:core", "--to", root, "--strict")
	if got := exitCodeFor(err); got != exitcode.Conflict {
		t.Fatalf("--strict did not promote a warning finding: exit = %d, want %d", got, exitcode.Conflict)
	}
}

// @codex on #652: os.ReadDir does not follow symlinks, so a SYMLINKED skill
// directory reports IsDir() == false while its SKILL.md reads fine through the
// link. Gating the walk on IsDir() made an installed skill invisible — and an
// invisible file comes back `never-exported`, which on the export path means
// overwriting somebody's linked file instead of leaving it alone.
func TestSkillStatusFollowsASymlinkedSkillDirectory(t *testing.T) {
	if runtime.GOOS == "windows" {
		t.Skip("symlink creation needs privilege on Windows")
	}
	root := t.TempDir()
	elsewhere := t.TempDir()
	writeSkillFile(t, elsewhere, "hadron-example", statusNodeID)
	if err := os.Symlink(filepath.Join(elsewhere, "hadron-example"), filepath.Join(root, "linked-skill")); err != nil {
		t.Skipf("cannot create symlink: %v", err)
	}

	_, captured, err := runSkillStatus(t, map[string]string{
		"SkillPlan": skillPlanResp(`"current"`, "false", ""),
	}, "-m", "hrn:mem:hadronmemory.com:core", "--to", root, "--json")
	if err != nil {
		t.Fatalf("status errored: %v", err)
	}
	files := sentFiles(t, captured)
	if len(files) != 1 {
		t.Fatalf("a symlinked skill directory was skipped: %v", files)
	}
	if files[0]["dirName"] != "linked-skill" {
		t.Errorf("dirName = %v, want the LINK's name (that is where the host loads it from)", files[0]["dirName"])
	}
	if files[0]["nodeId"] != statusNodeID {
		t.Errorf("the linked file's provenance did not travel: %v", files[0])
	}
}

// Dropping the IsDir() gate means a plain FILE sitting in the root is now
// opened as if it were a directory. It must still be a silent non-skill, not
// an "unreadable" row — otherwise every stray README in a skills root becomes
// drift.
func TestSkillStatusIgnoresAPlainFileInTheSkillsRoot(t *testing.T) {
	root := t.TempDir()
	if err := os.WriteFile(filepath.Join(root, "README.md"), []byte("not a skill"), 0o600); err != nil {
		t.Fatal(err)
	}
	out, captured, err := runSkillStatus(t, map[string]string{
		"SkillPlan": `{"data":{"skillPlan":{"scanned":0,"judged":0,"entries":[],"orphans":[]}}}`,
	}, "-m", "hrn:mem:hadronmemory.com:core", "--to", root, "--json")
	if err != nil {
		t.Fatalf("status errored: %v\n%s", err, out)
	}
	if files := sentFiles(t, captured); len(files) != 0 {
		t.Errorf("a plain file in the root was treated as a skill: %v", files)
	}
	var dto struct {
		Unreadable []struct{ Dir string } `json:"unreadable"`
	}
	if err := json.Unmarshal([]byte(out), &dto); err != nil {
		t.Fatal(err)
	}
	if len(dto.Unreadable) != 0 {
		t.Errorf("a stray file became an unreadable row: %+v", dto.Unreadable)
	}
}

// @copilot on #652: --strict must promote the RENDERED severity too, not only
// the exit code. `skill lint --strict` rewrites the finding to "error", so
// leaving it "warning" in status's --json has the two verbs disagree about the
// same finding — the exit code saying promoted and the row saying not.
func TestSkillStatusStrictPromotesTheRenderedSeverityToo(t *testing.T) {
	root := t.TempDir()
	warning := `[{"rule":"skill-description-no-trigger","severity":"warning","message":"no use-when phrasing","urn":"` +
		statusSourceURN + `","memory":"hrn:mem:hadronmemory.com:core"}]`
	severities := func(t *testing.T, out string) []string {
		t.Helper()
		var dto struct {
			Entries []struct {
				Findings []struct{ Severity string } `json:"findings"`
			} `json:"entries"`
		}
		if err := json.Unmarshal([]byte(out), &dto); err != nil {
			t.Fatalf("output not JSON: %v\n%s", err, out)
		}
		var got []string
		for _, e := range dto.Entries {
			for _, f := range e.Findings {
				got = append(got, f.Severity)
			}
		}
		return got
	}

	out, _, _ := runSkillStatus(t, map[string]string{
		"SkillPlan": skillPlanResp(`"current"`, "false", warning),
	}, "-m", "hrn:mem:hadronmemory.com:core", "--to", root, "--json", "--strict")
	if got := severities(t, out); len(got) != 1 || got[0] != "error" {
		t.Errorf("--strict did not promote the rendered severity: %v", got)
	}
	// Control: without --strict it stays a warning, or "promotion" is just a
	// constant.
	out2, _, err := runSkillStatus(t, map[string]string{
		"SkillPlan": skillPlanResp(`"current"`, "false", warning),
	}, "-m", "hrn:mem:hadronmemory.com:core", "--to", root, "--json")
	if err != nil {
		t.Fatalf("status errored: %v", err)
	}
	if got := severities(t, out2); len(got) != 1 || got[0] != "warning" {
		t.Errorf("without --strict the severity must stay warning: %v", got)
	}
}
